---

- name: install homebrew via the curl oneliner
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/bin/brew

- name: update and upgrade homebrew
  homebrew: update_homebrew=yes upgrade_all=yes

- name: tap caskroom/cask
  homebrew_tap: tap=caskroom/cask state=present

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: tap homebrew/services
  homebrew_tap: tap=homebrew/services state=present
