---

- name: install homebrew via the curl oneliner
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/bin/brew

- name: update and upgrade homebrew
  homebrew: update_homebrew=yes upgrade_all=yes

- name: tap caskroom
  homebrew_tap: tap={{item}} state=present
  with_items:
    - caskroom/cask
    - caskroom/versions
  # ansible has a bug where taps succeed but look like a failure 
  # https://github.com/ansible/ansible/issues/40853
  ignore_errors: yes

- name: tap homebrew/services
  homebrew_tap: tap=homebrew/services state=present
  # ansible has a bug where taps succeed but look like a failure 
  # https://github.com/ansible/ansible/issues/40853
  ignore_errors: yes
